### ISSUE TITLE
😈 [Feature Enhancement] - fix memory leak warnings

### ISSUE THREAD

**Issue by KlausMikhaelson** [ethereum-push-notification-service/push-dapp#1388]
### Feature name

following good practices to remove warnings and errors from the dapp

### Describe the Enhancement

When we open the dapp it creates multiple warnings and errors so we have to fix them

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by FaybianB** [comment]
Hello Satyam, may I be assigned this issue?

**Comment by KlausMikhaelson** [comment]
Hey @FaybianB sure will assign it to you!, let me know if you have any questions regarding the same!

**Comment by FaybianB** [comment]
Hey Satyam,

I'm having trouble getting the development environment set up by following the instructions in the Getting Started and Contributors section.

I experience one of these two runtime errors when I try to run the app via `yarn start`:

```
Uncaught runtime errors:

ERROR
Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at http://localhost:3000/static/js/bundle.js:24298:22
    at Array.forEach (<anonymous>)
    at getWeb3OnboardChains (http://localhost:3000/static/js/bundle.js:24294:65)
    at ./src/connectors/web3Onboard.tsx (http://localhost:3000/static/js/bundle.js:24498:77)
    at options.factory (http://localhost:3000/static/js/bundle.js:874496:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:873884:33)
    at fn (http://localhost:3000/static/js/bundle.js:874153:21)
    at ./src/index.js (http://localhost:3000/static/js/bundle.js:30492:82)
    at options.factory (http://localhost:3000/static/js/bundle.js:874496:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:873884:33)
   ```
    
OR
    
 ```
 Uncaught runtime errors:

ERROR
reactSpring.useSpring is not a function
TypeError: reactSpring.useSpring is not a function
    at DarkModeSwitch (http://localhost:3000/static/js/bundle.js:613582:39)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:372631:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:375114:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:376167:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:363208:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:363252:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:363307:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:380298:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:379309:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:379254:9)
 ```
 
 These errors alternate, depending on my environment setup here:
 
 
 ```
# REACT_APP needs to be appended to use env in react app
# NODE_ENV can be development or production | production makes a super optimized dapp experience
REACT_APP_NODE_ENV=production

# DEPLOY_ENN can be LOCALHOST, DEV, STAGING, PROD, W2W or ALPHA
REACT_APP_DEPLOY_ENV=DEV
 ```
 
 I have my Infura API Keys defined as well as my WalletConnect project ID.
 
 I've ran `yarn install` so I believe I should have all of the packages.
 
I don't have access to the Discord for troubleshooting because the invites have expired.

Do you have any advice on how I can get passed these issues and get the project setup?
